// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
let linux_EINTR : Int = 4

///|
let linux_ENOENT : Int = 2

///|
let linux_EEXIST : Int = 17

///|
let linux_EACCES : Int = 13

///|
let linux_ECONNREFUSED : Int = 111

///|
let linux_ENOTDIR : Int = 20

///|
let linux_ENOTSUP : Int = 95

///|
let linux_EAGAIN : Int = 11

///|
let linux_EINPROGRESS : Int = 115

///|
let linux_EWOULDBLOCK : Int = linux_EAGAIN
