// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
let windows_ERROR_IO_INCOMPLETE : Int = 996

///|
let windows_ERROR_IO_PENDING : Int = 997

///|
let windows_ERROR_FILE_NOT_FOUND : Int = 2

///|
let windows_ERROR_PATH_NOT_FOUND : Int = 3

///|
let windows_ERROR_FILE_EXISTS : Int = 80

///|
let windows_ERROR_ALREADY_EXISTS : Int = 183

///|
let windows_ERROR_ACCESS_DENIED : Int = 5

///|
let windows_ERROR_CONNECTION_REFUSED : Int = 1225

///|
let windows_ERROR_NOTIFY_ENUM_DIR : Int = 1022

///|
let windows_ERROR_DIRECTORY : Int = 267

///|
let windows_ERROR_NOT_SUPPORTED : Int = 50

///|
let windows_ERROR_BROKEN_PIPE : Int = 109
