// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
pub let windows_ERROR_IO_INCOMPLETE : Int = 996

///|
pub let windows_ERROR_IO_PENDING : Int = 997

///|
pub let windows_ERROR_FILE_NOT_FOUND : Int = 2

///|
pub let windows_ERROR_PATH_NOT_FOUND : Int = 3

///|
pub let windows_ERROR_FILE_EXISTS : Int = 80

///|
pub let windows_ERROR_ALREADY_EXISTS : Int = 183

///|
pub let windows_ERROR_ACCESS_DENIED : Int = 5

///|
pub let windows_ERROR_CONNECTION_REFUSED : Int = 1225

///|
pub let windows_ERROR_NOTIFY_ENUM_DIR : Int = 1022

///|
pub let windows_ERROR_DIRECTORY : Int = 267

///|
pub let windows_ERROR_NOT_SUPPORTED : Int = 50

///|
pub let windows_ERROR_OPERATION_ABORTED : Int = 995

///|
pub let windows_ERROR_LOCK_VIOLATION : Int = 33

///|
pub let windows_ERROR_HANDLE_EOF : Int = 38

///|
pub let windows_ERROR_BROKEN_PIPE : Int = 109
