// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
pub let macos_EINTR : Int = 4

///|
pub let macos_ENOENT : Int = 2

///|
pub let macos_EEXIST : Int = 17

///|
pub let macos_EACCES : Int = 13

///|
pub let macos_ECONNREFUSED : Int = 61

///|
pub let macos_ENOTDIR : Int = 20

///|
pub let macos_ENOTSUP : Int = 45

///|
pub let macos_EAGAIN : Int = 35

///|
pub let macos_EINPROGRESS : Int = 36

///|
pub let macos_EWOULDBLOCK : Int = macos_EAGAIN
