name: check

on:
  push:
    branches:
      - main
  pull_request:

env:
  MOONBIT_ASYNC_CHECK_FD_LEAK: 1

jobs:
  stable-build:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]

    runs-on: ${{ matrix.os }}
    continue-on-error: false
    timeout-minutes: 10
    steps:
      - name: disable auto CRLF
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: '>=22.4.0'
      - name: install MSVC (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: install (Unix)
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: install (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: moon update
        run: |
          moon update

      - name: moon check
        run: moon check --deny-warn

      - name: moon test
        run: moon test || true

      - name: moon test (release)
        run: moon test --release || true

      - name: moon test (release) (second run)
        run: moon test --release || true

      - name: moon test (second run)
        run: moon test || true

  nightly-build:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]

    runs-on: ${{ matrix.os }}
    continue-on-error: false
    timeout-minutes: 10
    steps:
      - name: disable auto CRLF
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: '>=22.4.0'

      - name: install MSVC (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: install (Unix)
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s nightly
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: install (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          MOONBIT_INSTALL_VERSION: nightly
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: moon update
        run: |
          moon update

      - name: moon check
        run: moon check

      - name: moon test
        run: moon test || true

      - name: moon test (release)
        run: moon test --release || true

      - name: moon test (release) (second run)
        run: moon test --release || true

      - name: moon test (second run)
        run: moon test || true
